compressionLevel: mixed

enableGlobalCache: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  local-pkg@*:
    dependencies:
      "@vitest/coverage-c8": "*"
  vite@*:
    dependencies:
      supports-color: "*"

pnpEnableEsmLoader: true

pnpMode: loose

supportedArchitectures:
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.2.2.cjs
